In [127]:
import pandas as pd
from sentence_transformers import SentenceTransformer
import numpy as np

In [128]:
df = pd.read_excel("dados.xlsx")
df.head()

,LINK,ID da resposta,Data de envio,Última página,Idioma inicial,Semente,Código de Acesso,Data de início,Data da última ação,GENERO,...,ENV1,ENV2,ENV3,ENV4,ENV5,ENV6,ENV7,ENV8,ENV9,ENV10
0,INT,568,2021-06-20 15:00:50,7,pt-BR,1767601499,uB3EaV9IXANbGvm,2021-06-20 14:55:17,2021-06-20 15:00:49,Feminino,...,1,7,1,5,7,5,1,6,7,5
1,EXT,167,2021-05-21 22:10:05,7,pt-BR,1839169195,2021-05-21 21:59:31,2021-05-21 22:10:05,NaN,Feminino,...,3,3,4,1,4,4,4,3,3,3
2,INT,489,2021-06-20 11:19:30,7,pt-BR,258990084,BgKQgz43AnBGl68,2021-06-20 11:13:00,2021-06-20 11:19:30,Feminino,...,7,7,7,7,7,7,7,7,7,7
3,INT,536,2021-06-20 13:19:52,7,pt-BR,1424695604,wDN4DUIbrCgBWaG,2021-06-20 13:05:17,2021-06-20 13:19:52,Feminino,...,1,6,4,5,3,5,5,7,1,7
4,INT,486,2021-06-20 11:07:55,7,pt-BR,667378996,8vgAKmEjIZKMDvf,2021-06-20 11:03:18,2021-06-20 11:07:55,Masculino,...,7,7,7,7,4,7,5,6,7,7

In [129]:
df[df.columns[21]].head()

0    Coletivo das Artes Motirô
1                Teatro mágico
2                     Cineritz
3                          NaN
4                          NaN
Name: Se você segue algum perfil de espaço cultural no Instagram, por favor, se puder, insira aqui o nome do perfil que considera acompanhar com maior frequência., dtype: object

In [130]:
print(df[df.columns[21]].isnull().sum())  # Verifique se há valores nulos
df[df.columns[21]] = df[df.columns[21]].fillna("Não informado")

79

In [131]:
df[df.columns[21]].head()

0    Coletivo das Artes Motirô
1                Teatro mágico
2                     Cineritz
3                Não informado
4                Não informado
Name: Se você segue algum perfil de espaço cultural no Instagram, por favor, se puder, insira aqui o nome do perfil que considera acompanhar com maior frequência., dtype: object

In [132]:
from sklearn.feature_extraction.text import CountVectorizer
vectorizer = CountVectorizer()

vetorizacao = vectorizer.fit_transform(df[df.columns[21]])  # Acessando a coluna corretamente
print(vectorizer.get_feature_names_out())

['196sonhos' '26' '9gag' '_ars_mundi' 'acontece' 'acreditar' 'adoro'
 'afropunk' 'agostinho' 'alguns' 'alimentam' 'além' 'amanhã' 'anchieta'
 'andrade' 'antofagica' 'aoca' 'apoena' 'aquelefilme' 'araçá' 'arch'
 'archaeologyart' 'arquitetos' 'arquivo' 'ars' 'art' 'art1' 'arte'
 'artemanha' 'artes' 'artista' 'artistas' 'artmotive' 'assis' 'atelier'
 'ateliês' 'atleticaedf' 'audio' 'augusto' 'aymoré' 'ballet' 'banco'
 'bandeira' 'banguê' 'barra' 'bateko' 'belas' 'belezascapixabas'
 'benedito' 'bh' 'biblioteca' 'bibliotecadecariacica' 'bibliotecas'
 'bibliotecaviladoprogresso' 'bienal' 'blx_bibliotecas_de_lisboa'
 'botânico' 'br' 'braga' 'brasil' 'brasileira' 'brasilemmapas' 'broadway'
 'brotas' 'bwayvideos' 'cabeça' 'cafecomletras' 'café' 'calcasadasartes'
 'camarata' 'camargo' 'camerata' 'canal' 'cantiga' 'capixaba'
 'capixabadagema' 'cariacica' 'carlos' 'casa' 'casa7' 'casadebambavix'
 'casafiatdecultura' 'casas' 'casasdecultura' 'cast' 'catete' 'cbn' 'ccbb'
 'ccbnb' 'ccmarioquintana' 'cefd' 'celular' 'centre' 'centro' 'choro'
 'cia' 'ciencia' 'cine' 'cineclubemetropolis' 'cinejardins'
 'cinejardinsoficial' 'cinema' 'cinemarcado' 'cinemarck' 'cinemark'
 'cinemarkoficial' 'cineritz' 'circovoador' 'cirquedusolei' 'cirurgica'
 'ciência' 'ciências' 'classical' 'clube' 'cláudia' 'clóvis' 'coletivo'
 'colker' 'com' 'companhia' 'concertotribanco' 'contemporânea' 'copy_link'
 'cor' 'cpad' 'criança' 'cristã' 'crítica' 'cultura' 'culturaespirita'
 'culturais' 'cultural' 'culturas' 'curta' 'da' 'daily' 'danterritorio'
 'dança' 'das' 'de' 'deborah' 'descarregado' 'descobrindo' 'desconhecidos'
 'dissw' 'do' 'edu' 'educamuseu' 'elaesoababa' 'elemmental' 'eletronica'
 'eliziário' 'em' 'emusp' 'enredadas' 'es' 'escola' 'escolabasileufranca'
 'escolares' 'escolas' 'espacocultural512' 'espaço' 'espírito' 'estado'
 'estação' 'está' 'etc' 'extracts' 'falabela' 'famosas' 'fatos'
 'festivais' 'festival' 'filme' 'filmes' 'filosofica' 'flamenco' 'flip'
 'fluante' 'flutuante' 'fora' 'forró' 'fotogaleria' 'fotógrafos' 'freitas'
 'fundação' 'fundição' 'gaeu' 'gal' 'galeria' 'gallery' 'galpão' 'gap'
 'gazeta' 'geopizza' 'geral' 'gesan' 'ghmassena' 'globalizei' 'gloria'
 'glória' 'gogh' 'gomes' 'gota' 'grupo' 'guaçui' 'guggenheim' 'gêmeos'
 'hamersmi' 'hesed' 'historia' 'história' 'histórico' 'hitz' 'homero'
 'homônimos' 'horto' 'https' 'ia' 'ibere' 'icedbrasil' 'iconha' 'iicrio'
 'ilha' 'improviso' 'infantil' 'informado' 'inhotim' 'inma' 'inox'
 'instagram' 'instituto' 'iphangovbr' 'isadora' 'isolamento' 'itaú'
 'janeiro' 'jardim' 'jardins' 'juiz' 'junho' 'junqueira' 'kinoplex'
 'kroller' 'kura' 'lausanne' 'lem' 'lembro' 'limeira' 'liverpub'
 'livraria' 'livrarias' 'livro' 'louvre' 'lugares' 'lume' 'lurix' 'lá'
 'língua' 'ma' 'mac' 'madeira' 'maes' 'maesmuseu' 'malokaespacocultural'
 'mam' 'mamute' 'mar' 'margs' 'maria' 'maré' 'mas' 'masp' 'massena' 'mast'
 'mateus' 'mathias' 'matias' 'mcv' 'me' 'meioambientees' 'mestre'
 'metropolis' 'metrópolis' 'meu' 'miguel' 'miradas' 'mom' 'moma'
 'montanamuseum' 'mosaico' 'motirô' 'mucane' 'muitos' 'muller' 'mundo'
 'municipal' 'muriaé' 'museelouvre' 'museeorsay' 'museodoprado' 'muses'
 'museu' 'museudoamanha' 'museudoipiranga' 'museum' 'museus' 'music'
 'musselouvre' 'mágico' 'mário' 'mãos' 'música' 'músicas' 'músicos' 'na'
 'nacional' 'naldojuniorartwork' 'nao' 'nara' 'nasa' 'net' 'networking'
 'new' 'nordeste' 'nordestino' 'nunes' 'nupesan' 'não' 'núcleo' 'oa'
 'obra' 'obras' 'oficial' 'online' 'opera' 'orquestra' 'os' 'osesp'
 'osgemeos' 'oswald' 'oteatromagico' 'ouro' 'oá' 'palaciodasartes'
 'palácio' 'para' 'paramount' 'parede' 'paris' 'particular' 'paulo'
 'perfeitos' 'perfil' 'perfis' 'pesquisa_fapesp' 'pinacoteca'
 'pinacotecasp' 'plásticos' 'pmvv' 'poeira' 'poema' 'poesiooo' 'pompidou'
 'ponto' 'popcultureangel' 'porta' 'porto' 'portuguesa' 'pos' 'preto'
 'privilege' 'prix' 'produções' 'progresso' 'projeto' 'projetos' 'pé' 'pó'
 'pública' 'público' 'que' 'queensland' 'rangel' 'razões' 'regionalal'
 'remoções' 'renato' 'reportagens' 'república' 'revolushow' 'ribeirão'
 'rio' 'rj' 'roda' 'roesler' 'ruschi' 'russo' 'ruth' 'sacra' 'sala'
 'salgado' 'samba' 'santo' 'schneider' 'scientists' 'se' 'sebo' 'sedac_rs'
 'serra' 'sertanejobr' 'sesc' 'sescespiritosanto' 'sescgloria' 'sesi'
 'sesiculturaes' 'seus' 'shopping' 'shows' 'siccastelo' 'sigo' 'sine'
 'sinfônica' 'sinhá' 'sm' 'soca' 'solineuras' 'soma' 'soupomerano' 'sp'
 'staelmagesckcentroartistico' 'suplementope' 'são' 'tate' 'tcg' 'teatro'
 'teatromrubembraga' 'teatroufes' 'teatrovocacionalceujmurilo' 'tem'
 'terapias' 'theatro' 'themuseumofmodernart' 'theodoro' 'tribuna'
 'trilhandopoa' 'tunga' 'tv' 'tvcultura' 'tvgazeta' 'ufes' 'ufesoficial'
 'um' 'uma' 'universitário' 'utm_medium' 'vale' 'van' 'viagens' 'vida'
 'vila' 'visite' 'visuais' 'visual' 'viva' 'vivoriorj' 'voltadas' 'vários'
 'wb' 'www' 'zoobotânico']

In [133]:
print(vetorizacao.toarray()[0])

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]

In [134]:
df.drop(df.columns[21],axis=1, inplace=True)

In [135]:
df[df.columns[21]].head()

0    7
1    1
2    1
3    1
4    1
Name: CON1, dtype: int64

In [136]:
espaco_cultural = pd.DataFrame(vetorizacao.toarray())

In [137]:
espaco_cultural.head()

,0,1,2,3,4,5,6,7,8,9,...,461,462,463,464,465,466,467,468,469,470
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [138]:
df = pd.concat([df,espaco_cultural], axis = 1)

In [139]:
df.head()

,LINK,ID da resposta,Data de envio,Última página,Idioma inicial,Semente,Código de Acesso,Data de início,Data da última ação,GENERO,...,461,462,463,464,465,466,467,468,469,470
0,INT,568,2021-06-20 15:00:50,7,pt-BR,1767601499,uB3EaV9IXANbGvm,2021-06-20 14:55:17,2021-06-20 15:00:49,Feminino,...,0,0,0,0,0,0,0,0,0,0
1,EXT,167,2021-05-21 22:10:05,7,pt-BR,1839169195,2021-05-21 21:59:31,2021-05-21 22:10:05,NaN,Feminino,...,0,0,0,0,0,0,0,0,0,0
2,INT,489,2021-06-20 11:19:30,7,pt-BR,258990084,BgKQgz43AnBGl68,2021-06-20 11:13:00,2021-06-20 11:19:30,Feminino,...,0,0,0,0,0,0,0,0,0,0
3,INT,536,2021-06-20 13:19:52,7,pt-BR,1424695604,wDN4DUIbrCgBWaG,2021-06-20 13:05:17,2021-06-20 13:19:52,Feminino,...,0,0,0,0,0,0,0,0,0,0
4,INT,486,2021-06-20 11:07:55,7,pt-BR,667378996,8vgAKmEjIZKMDvf,2021-06-20 11:03:18,2021-06-20 11:07:55,Masculino,...,0,0,0,0,0,0,0,0,0,0

In [140]:
df = df.drop(df.columns[[1,2,3,4,5,6,7,8]], axis=1)
df.head()

,LINK,GENERO,IDADE,RENDA,ESCOLARIDADE,COMP/CEL,TEM INSTA?,Com qual frequência acessa o aplicativo? [Eventualmente],Com qual frequência acessa o aplicativo? [Até 1 vez por semana],Com qual frequência acessa o aplicativo? [Mais de uma vez por semana],...,461,462,463,464,465,466,467,468,469,470
0,INT,Feminino,30,Acima de 3 e até 5 salários mínimos,Mestrado/Doutorado,Celular,Sim,Não,Não,Não,...,0,0,0,0,0,0,0,0,0,0
1,EXT,Feminino,35,Acima de 5 e até 10 salários mínimos,Pós-Graduação,Celular,Sim,Não,Não,Não,...,0,0,0,0,0,0,0,0,0,0
2,INT,Feminino,29,Até 1 salário mínimo,Ensino Superior,Celular,Sim,Sim,Não,Não,...,0,0,0,0,0,0,0,0,0,0
3,INT,Feminino,28,Até 1 salário mínimo,Ensino Médio,Celular,Sim,Não,Não,Não,...,0,0,0,0,0,0,0,0,0,0
4,INT,Masculino,36,Acima de 3 e até 5 salários mínimos,Ensino Superior,Computador/Notebook,Sim,Não,Não,Não,...,0,0,0,0,0,0,0,0,0,0

In [141]:
p = 0
for i in range(df.shape[1]):
    num = df[df.columns[i]].isnull().sum()

    if(num != 0):
        print(i)
        p+=1
print(f"Tem {p} colunas com alguns valores nulos")

1
Tem 1 colunas com alguns valores nulos

In [142]:
df["GENERO"] = df["GENERO"].fillna("Desconhecido")

In [143]:
#print(df[df.columns[4]].isnull().sum())  # Verifique se há valores nulos
#df[df.columns[4]] = df[df.columns[4]].fillna("sem data")

In [144]:
df["GENERO"].head()

0     Feminino
1     Feminino
2     Feminino
3     Feminino
4    Masculino
Name: GENERO, dtype: object

In [145]:
df.head()

,LINK,GENERO,IDADE,RENDA,ESCOLARIDADE,COMP/CEL,TEM INSTA?,Com qual frequência acessa o aplicativo? [Eventualmente],Com qual frequência acessa o aplicativo? [Até 1 vez por semana],Com qual frequência acessa o aplicativo? [Mais de uma vez por semana],...,461,462,463,464,465,466,467,468,469,470
0,INT,Feminino,30,Acima de 3 e até 5 salários mínimos,Mestrado/Doutorado,Celular,Sim,Não,Não,Não,...,0,0,0,0,0,0,0,0,0,0
1,EXT,Feminino,35,Acima de 5 e até 10 salários mínimos,Pós-Graduação,Celular,Sim,Não,Não,Não,...,0,0,0,0,0,0,0,0,0,0
2,INT,Feminino,29,Até 1 salário mínimo,Ensino Superior,Celular,Sim,Sim,Não,Não,...,0,0,0,0,0,0,0,0,0,0
3,INT,Feminino,28,Até 1 salário mínimo,Ensino Médio,Celular,Sim,Não,Não,Não,...,0,0,0,0,0,0,0,0,0,0
4,INT,Masculino,36,Acima de 3 e até 5 salários mínimos,Ensino Superior,Computador/Notebook,Sim,Não,Não,Não,...,0,0,0,0,0,0,0,0,0,0

In [146]:
#dfi = pd.DataFrame()
#dummies = pd.get_dummies(df["IDADE"], prefix="IDADE")
# Concatenar as colunas dummy ao DataFrame auxiliar
#dfi = pd.concat([dfi, dummies], axis=1)
# Remover as colunas originais após a iteração
#df = df.drop(columns=["IDADE"])

# Concatenar df2 ao df original corretamente
#df = pd.concat([df, dfi], axis=1)

In [147]:
# Lista para armazenar colunas a serem removidas
drop_columns = []
df2 = pd.DataFrame()  # Criar um DataFrame vazio para armazenar as novas colunas

for col in df.columns:
    if not pd.api.types.is_numeric_dtype(df[col]):  # Verifica se a coluna é numérica
        print(f"Coluna não numérica: {col}")
        # Criar colunas dummy com um prefixo
        dummies = pd.get_dummies(df[col], prefix=col)
        # Concatenar as colunas dummy ao DataFrame auxiliar
        df2 = pd.concat([df2, dummies], axis=1)
        # Armazenar a coluna original para remoção posterior
        drop_columns.append(col)

# Remover as colunas originais após a iteração
df = df.drop(columns=drop_columns)

# Concatenar df2 ao df original corretamente
df = pd.concat([df, df2], axis=1)

# Opcional: resetar o índice se necessário
df.reset_index(drop=True, inplace=True)

Coluna não numérica: LINK
Coluna não numérica: GENERO
Coluna não numérica: RENDA
Coluna não numérica: ESCOLARIDADE
Coluna não numérica: COMP/CEL
Coluna não numérica: TEM INSTA?
Coluna não numérica: Com qual frequência acessa o aplicativo? [Eventualmente]
Coluna não numérica: Com qual frequência acessa o aplicativo? [Até 1 vez por semana]
Coluna não numérica: Com qual frequência acessa o aplicativo? [Mais de uma vez por semana]
Coluna não numérica: Com qual frequência acessa o aplicativo? [Pelo menos uma vez por dia]
Coluna não numérica: Com qual frequência acessa o aplicativo? [Mais de uma vez por dia]
Coluna não numérica: Você segue algum perfil de espaço cultural (Ex.: Teatro, Cinema, Casa de Show, Museu, Galeria de Arte, etc...) no Instagram?

In [148]:
df2.head()

,LINK_EXT,LINK_INT,GENERO_Desconhecido,GENERO_Feminino,GENERO_Masculino,RENDA_Acima de 1 e até 3 salários mínimos,RENDA_Acima de 10 e até 15 salários mínimos,RENDA_Acima de 15 e até 20 salários mínimos,RENDA_Acima de 20 salários mínimos,RENDA_Acima de 3 e até 5 salários mínimos,...,Com qual frequência acessa o aplicativo? [Eventualmente]_Sim,Com qual frequência acessa o aplicativo? [Até 1 vez por semana]_Não,Com qual frequência acessa o aplicativo? [Até 1 vez por semana]_Sim,Com qual frequência acessa o aplicativo? [Mais de uma vez por semana]_Não,Com qual frequência acessa o aplicativo? [Mais de uma vez por semana]_Sim,Com qual frequência acessa o aplicativo? [Pelo menos uma vez por dia]_Não,Com qual frequência acessa o aplicativo? [Pelo menos uma vez por dia]_Sim,Com qual frequência acessa o aplicativo? [Mais de uma vez por dia]_Não,Com qual frequência acessa o aplicativo? [Mais de uma vez por dia]_Sim,"Você segue algum perfil de espaço cultural (Ex.: Teatro, Cinema, Casa de Show, Museu, Galeria de Arte, etc...) no Instagram?_Sim"
0,False,True,False,True,False,False,False,False,False,True,...,False,True,False,True,False,True,False,False,True,True
1,True,False,False,True,False,False,False,False,False,False,...,False,True,False,True,False,True,False,False,True,True
2,False,True,False,True,False,False,False,False,False,False,...,True,True,False,True,False,True,False,True,False,True
3,False,True,False,True,False,False,False,False,False,False,...,False,True,False,True,False,True,False,False,True,True
4,False,True,False,False,True,False,False,False,False,True,...,False,True,False,True,False,True,False,False,True,True

In [149]:
df.head()

,IDADE,CON1,CON2,CON3,CON4,CON5,CON6,CON7,INT1,INT2,...,Com qual frequência acessa o aplicativo? [Eventualmente]_Sim,Com qual frequência acessa o aplicativo? [Até 1 vez por semana]_Não,Com qual frequência acessa o aplicativo? [Até 1 vez por semana]_Sim,Com qual frequência acessa o aplicativo? [Mais de uma vez por semana]_Não,Com qual frequência acessa o aplicativo? [Mais de uma vez por semana]_Sim,Com qual frequência acessa o aplicativo? [Pelo menos uma vez por dia]_Não,Com qual frequência acessa o aplicativo? [Pelo menos uma vez por dia]_Sim,Com qual frequência acessa o aplicativo? [Mais de uma vez por dia]_Não,Com qual frequência acessa o aplicativo? [Mais de uma vez por dia]_Sim,"Você segue algum perfil de espaço cultural (Ex.: Teatro, Cinema, Casa de Show, Museu, Galeria de Arte, etc...) no Instagram?_Sim"
0,30,7,7,7,7,7,7,7,7,7,...,False,True,False,True,False,True,False,False,True,True
1,35,1,1,1,1,1,1,1,1,1,...,False,True,False,True,False,True,False,False,True,True
2,29,1,1,1,1,1,1,1,1,1,...,True,True,False,True,False,True,False,True,False,True
3,28,1,1,1,1,1,3,4,7,1,...,False,True,False,True,False,True,False,False,True,True
4,36,1,1,1,1,1,4,5,4,1,...,False,True,False,True,False,True,False,False,True,True

In [150]:
df[df.columns[-1]].value_counts()
# Converter a última coluna para inteiro
#df[df.columns[-1]] = df[df.columns[-1]].astype(int)

Você segue algum perfil de espaço cultural (Ex.: Teatro, Cinema, Casa de Show, Museu, Galeria de Arte, etc...) no Instagram?_Sim
True    315
Name: count, dtype: int64

In [151]:
df = df.drop(df.columns[-1], axis=1)

In [152]:
df.head()

,IDADE,CON1,CON2,CON3,CON4,CON5,CON6,CON7,INT1,INT2,...,Com qual frequência acessa o aplicativo? [Eventualmente]_Não,Com qual frequência acessa o aplicativo? [Eventualmente]_Sim,Com qual frequência acessa o aplicativo? [Até 1 vez por semana]_Não,Com qual frequência acessa o aplicativo? [Até 1 vez por semana]_Sim,Com qual frequência acessa o aplicativo? [Mais de uma vez por semana]_Não,Com qual frequência acessa o aplicativo? [Mais de uma vez por semana]_Sim,Com qual frequência acessa o aplicativo? [Pelo menos uma vez por dia]_Não,Com qual frequência acessa o aplicativo? [Pelo menos uma vez por dia]_Sim,Com qual frequência acessa o aplicativo? [Mais de uma vez por dia]_Não,Com qual frequência acessa o aplicativo? [Mais de uma vez por dia]_Sim
0,30,7,7,7,7,7,7,7,7,7,...,True,False,True,False,True,False,True,False,False,True
1,35,1,1,1,1,1,1,1,1,1,...,True,False,True,False,True,False,True,False,False,True
2,29,1,1,1,1,1,1,1,1,1,...,False,True,True,False,True,False,True,False,True,False
3,28,1,1,1,1,1,3,4,7,1,...,True,False,True,False,True,False,True,False,False,True
4,36,1,1,1,1,1,4,5,4,1,...,True,False,True,False,True,False,True,False,False,True

In [153]:
# Converte colunas booleanas para inteiros
#bool_cols = df.select_dtypes(include=['bool']).columns
#df[bool_cols] = df[bool_cols].astype(int)


# Identifica o nome da primeira coluna
col0 = df.columns[0]

# Normaliza somente a coluna 0
df[col0] = (df[col0] - df[col0].min()) / (df[col0].max() - df[col0].min())

In [154]:
df[col0].info()

<class 'pandas.core.series.Series'>
RangeIndex: 315 entries, 0 to 314
Series name: IDADE
Non-Null Count  Dtype
--------------  -----
315 non-null    float64
dtypes: float64(1)
memory usage: 2.6 KB

In [155]:
df.head()

,IDADE,CON1,CON2,CON3,CON4,CON5,CON6,CON7,INT1,INT2,...,Com qual frequência acessa o aplicativo? [Eventualmente]_Não,Com qual frequência acessa o aplicativo? [Eventualmente]_Sim,Com qual frequência acessa o aplicativo? [Até 1 vez por semana]_Não,Com qual frequência acessa o aplicativo? [Até 1 vez por semana]_Sim,Com qual frequência acessa o aplicativo? [Mais de uma vez por semana]_Não,Com qual frequência acessa o aplicativo? [Mais de uma vez por semana]_Sim,Com qual frequência acessa o aplicativo? [Pelo menos uma vez por dia]_Não,Com qual frequência acessa o aplicativo? [Pelo menos uma vez por dia]_Sim,Com qual frequência acessa o aplicativo? [Mais de uma vez por dia]_Não,Com qual frequência acessa o aplicativo? [Mais de uma vez por dia]_Sim
0,0.000022,7,7,7,7,7,7,7,7,7,...,True,False,True,False,True,False,True,False,False,True
1,0.000030,1,1,1,1,1,1,1,1,1,...,True,False,True,False,True,False,True,False,False,True
2,0.000020,1,1,1,1,1,1,1,1,1,...,False,True,True,False,True,False,True,False,True,False
3,0.000018,1,1,1,1,1,3,4,7,1,...,True,False,True,False,True,False,True,False,False,True
4,0.000032,1,1,1,1,1,4,5,4,1,...,True,False,True,False,True,False,True,False,False,True

In [156]:
from sklearn.decomposition import PCA
import numpy as np

# Empilhando as colunas para criar um único array 2D
array_2d = np.column_stack([df[col].values for col in df.columns])

# Aplica PCA para reduzir para 2 dimensões
pca = PCA(n_components=2, svd_solver='full')
X_transformed = pca.fit_transform(array_2d)

# Adiciona os resultados do PCA ao DataFrame
df['pca_1'] = X_transformed[:, 0]
df['pca_2'] = X_transformed[:, 1]

# Salvar as colunas pca_1 e pca_2 sem cabeçalhos
df[['pca_1', 'pca_2']].to_csv("data/input/dataset.txt", sep=" ", index=False, header=False)

# Exibe o DataFrame com os resultados
#print(df)

In [157]:
#np.savetxt("data/input/dataset.txt", df.values, fmt="%s")